### ISSUE TITLE
GitHub Actions 経由だと自動リリースに失敗する

### ISSUE THREAD

**Issue by inc2734** [inc2734/self-host-github-releases#1]
actions/upload-release-asset@v1 を使用。

```
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./snow-monkey.zip
        asset_name: snow-monkey.zip
        asset_content_type: application/zip
```

なぜか webhook のペイロードで `assets` が空で帰ってくるようになり、失敗する。無駄な処理かもしれないけどペイロードからじゃなくて API から再取得するように変更する。
